spring:
  cloud:
    vault:
      enabled: true
      uri: ${VAULT_URI::http://localhost:8200}
      token: ${VAULT_TOKEN:root}
      scheme: http
      ssl:
        is-enabled: false
      kv:
        enabled: true


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false